# 2. Numpy (Numerical Python)
Vector (Array) Vectirise Computing  
Matrices   
Array 2D and ND   
Type of Data  
Creat Array   
Indexing And Slicing  
Array 1D and ND  
Shape And Reshape  
Mathmatic  
Elementwise  
Aggragate  
Boolian 
Set  
Work on Array  
Work on Matrices  

### Importing the Modeles (numpy)
    !pip install numpy

    import numpy as np

In [1]:
import numpy as np

### 1. Vector , Matrices and Multidimensional Array

Use Numpy Lib for this section   
Numpy oder For function?
Numpy can use for this and Low Time for progress   
All data in Array hast one type und cant appden (add data) , that can help to time run   

In [24]:
np.ndarray? #help abaut method

SyntaxError: invalid syntax (1506997183.py, line 1)

create one array

In [7]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [8]:
type(data)

numpy.ndarray

In [9]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

Dimansion

In [11]:
data.ndim

2

Shape

In [13]:
data.shape

(3, 2)

Size

In [14]:
data.size

6

Type   


In [16]:
data.dtype

dtype('int64')

how mach bytes

In [15]:
data.nbytes

48

> 1.1. Data Type   

int -> int8 , 16, 32, 64  
unit -> 16, 32, 64  
bool 
float -> 16, 32, 64, 128   
complex -> 64, 128, 256

In [26]:
np.array([1, 2, 3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [32]:
np.array([1, 2, 3], dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [34]:
np.array([1, 2, 3], dtype=np.complex64)

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [39]:
# data kasting
data = np.array([1, 2, 3], dtype=np.float16)
data.dtype

dtype('float16')

In [40]:
data

array([1., 2., 3.], dtype=float16)

In [41]:
data = np.array(data, dtype=np.int8)
data

array([1, 2, 3], dtype=int8)

In [42]:
data = np.array([1, 2, 3], dtype=np.float16)

In [43]:
data

array([1., 2., 3.], dtype=float16)

.astype

In [44]:
data.astype(np.int8)

array([1, 2, 3], dtype=int8)

float + complex -> update type

In [46]:
d1 = np.array([1, 2, 3], dtype=np.float16)
d2 = np.array([1, 2, 3], dtype=np.complex64)
d1 + d2


array([2.+0.j, 4.+0.j, 6.+0.j], dtype=complex64)

Type of data is important  

\begin{align}
{x} & = -1\\
{y} & = \sqrt(x)\\
{Result} & = nan
\end{align}

In [47]:
np.sqrt(np.array([-1, 0, 1]))

C:\Users\user\Oracel19c\admin\orcl\Temp\ipykernel_6212\208196152.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [52]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

In [53]:
data = np.array([1, 2, 3], dtype=complex)

In [54]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [55]:
data.real

array([1., 2., 3.])

In [56]:
data.imag

array([0., 0., 0.])

> 1.2. Order of Array Data in Memory
row-major format : keyword argument `order= 'C'` |
column-major format : keyword argument `order= 'F'` 
    default format is row-major
    
> NumPy array attribute : `ndarray.strides`  

(in tihs code after run each byte = 8)
> Example: C-order array A with shape `(2, 3)` | data type : `int32` | total memory buffer for the array : `2 × 3 × 4 = 24`

> strides attribute of this array : `(4 × 3, 4 × 1) = (12, 4)` | `F` order , the strides : `(4, 8)`

> Stride 
> <img src="p09.PNG">
> [Ref](https://stackoverflow.com/questions/53097952/how-to-understand-numpy-strides-for-layman#:~:text=3%20Answers&text=To%20map%20the%20indices%20i,direction%2Fdimension%20of%20the%20array.)

In [57]:
a = np.arange(1, 10).reshape(3, 3)

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a.itemsize

8

In [60]:
a.size

9

In [61]:
a.nbytes

72

In [62]:
a.strides

(24, 8)

In [63]:
b = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]]).T

In [64]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Transpos cant chang data and change view by transpos

In [65]:
b.strides

(8, 24)

### 2. Creating Arrays
> Arrays Created from Lists and Other Array-Like Objects

In [ ]:
# list
data = np.array([1, 2, 3, 4])
print(f"dim : {data.ndim}, shape: {data.shape}")

dim : 1, shape: (4,)


In [ ]:
# tuple
data = np.array((1, 2, 3, 4))
print(f"dim : {data.ndim}, shape: {data.shape}")

dim : 1, shape: (4,)


In [ ]:
# set
data = np.array({1, 2, 3, 4})
print(data)
print(f"dim : {data.ndim}, shape: {data.shape}")

{1, 2, 3, 4}
dim : 0, shape: ()


In [72]:
data = np.array([[1, 2], [3, 4]])
print(data)
print(f"dim : {data.ndim}, shape: {data.shape}")

[[1 2]
 [3 4]]
dim : 2, shape: (2, 2)
